### ISSUE TITLE
Type mismatch. Found d?, expected (r?|num)

### ISSUE THREAD

**Issue by WernerLuiz92** [awilliamson/ic10-language-support#1]
First congratulations for the extension, it is very good and useful.
I'm getting an error when reading a device slot variable.
According to the game's Wiki, to read the slot variables, you must use the following syntax:
`ls r? d? num var` and my code is following this exact syntax and presents the error below:
`Type mismatch. Found d?, expected (r?|num)`
![image](https://user-images.githubusercontent.com/68384543/228659934-1012ed7a-02cd-43fd-82db-59992cbd707c.png)
![image](https://user-images.githubusercontent.com/68384543/228659975-42bd1e67-f8dc-4cc2-8ae9-3ccb543d7526.png)

**Comment by awilliamson** [comment]
Thanks @WernerLuiz92. Once @Xandaros releases latest fixes to the language server, I'll push through an update here :) Appreciate the testing and the detailed bug report.

**Comment by awilliamson** [comment]
Fixed by 876d8f868e7612739a7cd1154d0a8b93fe00909b
