### ISSUE TITLE
Missing support for name hash functions from April 2023 update

### ISSUE THREAD

**Issue by kaedys** [awilliamson/ic10-language-support#4]
Ref: https://steamdb.info/patchnotes/11088471/

The following operations are flagged as invalid:

```
lbn
sbn
lbns
lbs
snan
snanz
bnan
brnan
HASH("name")
```

For example, the following code works in-game, but is highlight as invalid in the below screenshots:

```
alias pump1 d0
alias pump2 d1

define TANKNAME HASH("Tank Oxygen")
define MAXPRESSURE 50000

start:
yield

lbn r0 272136332 TANKNAME Pressure Average
slt r0 r0 MAXPRESSURE

s db On r0
brdns pump1 2
s pump1 On r0
brdns pump2 2
s pump2 On r0

j start
```

<img width="423" alt="20230823-121716-904701" src="https://github.com/awilliamson/ic10-language-support/assets/9020449/a9841a2a-715d-4ce1-a7e1-aab887841490">
<img width="491" alt="20230823-121702-d539ec" src="https://github.com/awilliamson/ic10-language-support/assets/9020449/a3ca2960-094e-4ee3-839e-5273da837324">

(note: I added the additional commands from that April patch in the screenshot, I've not tested any of them except `lbn` directly in-game, however).

**Comment by Xandaros** [comment]
Already tracked in these issues:
https://github.com/Xandaros/ic10lsp/issues/24
https://github.com/Xandaros/ic10lsp/issues/21
https://github.com/Xandaros/ic10lsp/issues/18

Do tell me if anything isn't covered by these, though.

Keep in mind that this repo is for the VSCode integration of the language server. The actual language server is [ic10lsp](https://github.com/Xandaros/ic10lsp)

And yeah, I'm really behind there. Haven't really been playing Stationeers much lately, so my personal interest in updating it hasn't been very high. I should really get around to doing it, though - having valid code flagged as an error sucks.

**Comment by Xandaros** [comment]
> Derp, my bad >.<

Don't worry - I absolutely expected this to happen. I think it's insane that you need an entire addon for VSCode at all. Some other editors, you just point it at the language server and you're good.

But yes, it makes it confusing. Especially it's done by two separate people. But I don't use VSCode myself, so I didn't want to work on the integration :P

**Comment by kaedys** [comment]
Well, took a look at ic10lsp to see if I might be able to help, and ya no, Rust is still _way_ outside my realm of familiarity (my main language is Go, which is pretty starkly different than Rust >.<).  So RIP on that one.  Still, no pressure, hobby projects are hobby projects, after all.

**Comment by Xandaros** [comment]
I'm going to try and add the instructions in the next couple days. It should honestly be pretty straight-forward.
Adding `HASH` is an entirely different story, but I'll go for the low hanging fruit first.

I honestly don't think you need to know any rust for it - just copy what is already there for the other instructions, but fair enough. Setting up the project is not entirely trivial, I will admit.

If you want to help, though - a list of all the missing instructions and their signature would be immensely helpful :smile:

**Comment by kaedys** [comment]
Scanned through the Stationpedia and cross-referenced with the language server results.  I can't claim this is exhaustive, because I skipped checking functions that I was pretty sure were already covered (like the bazillion variants of branch).  Notably, there are a couple additional functions I wasn't aware of, and that are not included in any of the above issues (or this one's OP), such as `lr` and `not`.  The descriptions below are transcriptions directly from the Stationpedia.

Functions:
```
bnan a(r?|num) b(r?|num)
Branch to line b if a is not a number (NaN)

brnan a(r?|num) b(r?|num)
Relative branch to line b if a is not a number (NaN)

lbn r? deviceHash nameHash logicType batchMode
Loads LogicType from all output network devices with provided type and name hashes using the provided patch mode.  Average (0), Sum (1), Minimum (2), Maximum (3).  Can use either the word, or the number.

lbns r? deviceHash nameHash slotIndex logicSlotType batchMode
Loads LogicSlotType from slotIndex from all output network devices with provided type and name hashes using the provided batch mode.  Average (0), Sum (1), Minimum (2), Maximum (3).  Can use either the word, or the number.

lbs r? deviceHash slotIndex logicSlotType batchMode
Loads LogicSlotType from slotIndex from all output network devices with provided type hash using the provided batch mode.  Average (0), Sum (1), Minimum (2), Maximum (3).  Can use either the word, or the number.

lr r? d? reagentMod int
Loads reagent of device's ReagentMode where a hash of the reagent type to check for.  ReagentMode can be either Contents (0), Required (1), Recipe (2).  Can use either the word, or the number.

not r? a(r?|num)
Performs a bitwise logical NOT operation flipping each bit of the input value, resulting in the binary complement.  If a bit is 1, it becomes 0, and if a bit is 0, it becomes 1.

sbn deviceHash nameHash logicType r?
Stores register value to LogicType on all output network devices with provided type hash and name.

sbs deviceHash slotIndex logicSlotType r?
Stores register value to LogicSlotType on all output network devices with provided type hash in the provided slot.

sla r? a(r?|num) b(r?|num)
Performs a bitwise arithmetic left shift operation on the binary representation of a value.  It shifts the bits to the left and fills the vacated rightmost bits with a copy of the sign bit (the most significant bit).

sll r? a(r?|num) b(r?|num)
Performs a bitwise arithmetic left shift operation on the binary representation of a value.  It shifts the bits to the left and fills the vacated rightmost bits with zeros.

sra r? a(r?|num) b(r?|num)
Performs a bitwise arithmetic right shift operation on the binary representation of a value.  It shifts the bits to the right and fills the vacated leftmost bits with a copy of the sign bit (the most significant bit).

srl r? a(r?|num) b(r?|num)
Performs a bitwise arithmetic right shift operation on the binary representation of a value.  It shifts the bits to the right and fills the vacated leftmost bits with zeros).

snan r? a(r?|num)
Register = 1 if a is NaN, otherwise 0.

snanz r? a(r?|num)
Register = 0 if a is NaN, otherwise 1.

ss d? slotIndex logicSlotType r?
Stores register value to device stored in a slot LogicSlotType on device.
```

Constants:
```
nan - "quiet" not-a-number ("A constant representing 'not a number'. This constant technically provides a 'quiet' NaN, a signal NaN from some instructions will result in an exception and halt execution")
pinf - positive infinity
ninf - negative infinity
pi
deg2rad - pi/180, ~0.0174532923847437
rad2deg - 180/pi, ~57.2957801818848
epsilon - "A constant representing the smallest value representable in double precision", assuming the game is using standard IEEE representation, this would be 2^−52,  or ~2.22E-16
```

**Comment by Xandaros** [comment]
It was a bit longer than I expected, but I've now added all the missing instructions, with the sole exception of `lr`. That one needs some special consideration... I'll get around to it eventually.
Now you'll just need to wait for @awilliamson to update the VSCode extension :P

**Comment by Xandaros** [comment]
I have now also added `HASH`, the network syntax (e.g. `d2:3`), as well as binary and hexadecimal notation for numbers.

...and also, syntax errors are now highlighted as errors... no clue how that went unnoticed for so long.

The only big thing missing is `lr`. And UTF-16 support, but screw that, lol.

**Comment by awilliamson** [comment]
VSCode Extension updated to utilise 0.7.3. 

Looks good to close this, feel free to try it out and report issues. 

Annoyingly the VSCode extension ecosystem doesn't seem to support auto-updating of pre-packaged binaries. I'll try to work on something to auto-publish the extension each time, in lockstep with the base lsp.

**Comment by kaedys** [comment]
I honestly have no idea how the VSCode extension system works, but my workplace has spend much of the last year transitioning our CI system over to using Github Actions, and I'd think an Actions workflow would be able to automate type of thing without too much trouble.  Their trigger system is quite robust, and the entire thing is exceptionally extensible.
