### ISSUE TITLE
upgrade server

### ISSUE THREAD

**Issue by lspk** [awilliamson/ic10-language-support#6]
Hi,

Thank your for the plugin that make our lives easier

Could you upgrade to https://github.com/Xandaros/ic10lsp/releases/tag/v0.7.4 ?

Thanks

**Comment by awilliamson** [comment]
@lspk Done, see Release v0.7.4 https://github.com/awilliamson/ic10-language-support/releases/tag/v0.7.4 and also via vscode extension page.
